FROM ubuntu:latest

ENV HOME /root
WORKDIR /root
RUN apt-get update
RUN apt-get install -y --no-install-recommends nano
#RUN apt-get install -y --no-install-recommends psutils
#########################################################################################
ENTRYPOINT /bin/bash